### ISSUE TITLE
GCS: gcsf not included in Dockerfile

### ISSUE THREAD

**Issue by MartinBaumga** [rstudio/vetiver-python#165]
**Describe the bug**
When I prepare a Dockerfile with vetiver.prepare_docker for a Board in a google cloud storage bucket the package the vetiver_requirements.txt is missing the package gcsfs. Therefore the Run step is not successfull. Adding gcsfs manualy in the vetiver_requirements.txt resolves it. 

**To Reproduce**

Prepare Script:

import vetiver
import pins

board = pins.board_gcs('deployed_model', allow_pickle_read=True)
vetiver.prepare_docker(board, "deployed_model_test", path="cloud_run/rest_api/app")

In console:
sudo docker build -t model.
sudo docker run model

**Expected behavior**
Include gcsfs in vetiver_requirements.txt after running vetiver.prepare_docker(board, "nk_churn_test", path="cloud_run/rest_api/app")

**Screenshots**
![image](https://user-images.githubusercontent.com/100121406/225860261-69e4802f-57fb-463f-ae2f-29014d143755.png)

**Desktop:**
 - OS: Linux Ubuntu
 - Version 22

**Comment by isabelizimm** [comment]
Hi there @MartinBaumga, thank you so much for this report! 

It looks like this is happening since vetiver is unaware of the backend pins is connecting to, so it is not tracking the requirements necessary to authenticate. 

Looking at the equivalent's of these packages in the R language, pins-r side has a `required_pkgs` [method for boards](https://github.com/rstudio/pins-r/blob/5a15a9e6810a5cea1ac7cfdb1e2712b1450919d9/R/board_gcs.R#L202), then vetiver-r aggregates those with the modeling requirements [when people run `vetiver_prepare_docker()`](https://github.com/rstudio/vetiver-r/blob/main/R/write-docker.R#L206).

I'll open up an issue in pins-python, so we can coordinate how to fix this!

**Comment by isabelizimm** [comment]
Fixed in #166, to be released in v0.2.1!
