### ISSUE TITLE
less vetiver in function names (?)

### ISSUE THREAD

**Issue by isabelizimm** [rstudio/vetiver-python#53]
When using this package, it can feel awkward typing `vetiver.vetiver_XXX` for many functions. On the R side, this makes sense as it better follows the naming conventions in the language, but it is often redundant when importing from vetiver-python. 

I am thinking about renaming a few functions (ie, maybe `vetiver_pin_write()` -> `vetiver.pin_write()`) to feel more fluent in use.

CC: @has2k1

**Comment by has2k1** [comment]
Following common practice in python for creating and saving objects, 
`vetiver_pin_read` should be the _classmethod_ `VetiverModel.from_pin()` and `vetiver_pin_write` should be the regular _method_ `VetiverModel.pin_write()`.

**Comment by isabelizimm** [comment]
> One thing we will want to be consistent on is how "pin" is used

What about `v.write_pin()` rather than `v.pin_write`/`v.to_pin`? Then it can be clear that the verb is write without it feeling redundant.

**Comment by juliasilge** [comment]
I think `v.to_pin` might be the best option if we want to make a change for that one now (vs. later when we can dispatch off the pinned object type, so we can do `board.pin_write(v)`). I worry about `v.pin_write` or `v.write_pin` because of the pins context, where the methods are for the board, not the pinned object type.

IMO it would be OK to make all these changes except the one for writing to a pin (keep `vetiver_pin_write(board, model)`), since we have planned changes for that later. I am also supportive of changing it twice, if you all think it's best and important. It just means more deprecation warnings, which are not a problem or bad.
